#!/usr/bin/env python

#    This file is part of Color Walk.
#
#    Color Walk is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    Color Walk is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Color Walk.  If not, see <http://www.gnu.org/licenses/>.

import sys, os, subprocess, threading, tempfile, shutil, time, optparse

import glib, gtk


try:
    import numpy
except ImportError:
    numpy = None


import ColorWalk

from ColorWalk import IMAGE_EXTENSIONS, DEFAULT_SIZE, FIT_BY_WIDTH

from ColorWalk import choose_file, find_average_border_color

from ColorWalk import find_ui_definition, new_pixbuf, preload_images, reload_all


class Window(gtk.Window):
    
    widgets = None
    worker = None
    lock = threading.Lock()
    preferences = ColorWalk.Preferences()
    
    default_background = None
    
    current_pixbuf = None
    prev_pixbuf = None
    next_pixbuf = None
    
    open_file = None
    index = 0
    images = []
    temp_dir = None
    browse_dir = None
    
    scale = FIT_BY_WIDTH
    width = 800
    width_old = None
    height = 800
    height_old = None
    maximized = False
    
    def __init__(self, ui, file=None):
        '''The Color Walk main window. Arguments: ui is the file path of a XML 
        user interface file, and the optional argument, file, is the path to a
        file to open.'''
        
        gtk.Window.__init__(self)
        
        # Load the widgets from the XML file:
        self.widgets = gtk.Builder()
        self.widgets.add_from_file(ui)
        
        # Window events:
        self.connect('delete-event', self.quit)
        self.connect('configure-event', self.window_resized)
        self.connect('key-press-event', self.key_pressed)
        self.connect('window-state-event', self.state_changed)
        
        # Tool button events:
        self.widgets.get_object('open_button').connect('clicked', self.open)
        self.widgets.get_object('close_button').connect('clicked', self.close)
        self.widgets.get_object('forward_button').connect('clicked', self.go_forward)
        self.widgets.get_object('fullscreen_button').connect('toggled', self.toggle_fullscreen)
        self.widgets.get_object('back_button').connect('clicked', self.go_back)
        self.widgets.get_object('normal_button').connect('toggled', self.toggle_scale)
        self.widgets.get_object('fit_button').connect('toggled', self.toggle_scale)
        self.widgets.get_object('about_button').connect('clicked', self.about)
        self.widgets.get_object('help_button').connect('clicked', self.help)
        self.widgets.get_object('prefs_button').connect('clicked', self.edit_preferences)
        
        # Context menu events:
        self.widgets.get_object('viewport').connect('button-press-event', self.image_clicked)
        self.widgets.get_object('context-menu-open').connect('activate', self.open)
        self.widgets.get_object('context-menu-close').connect('activate', self.close)
        self.widgets.get_object('context-menu-edit').connect('activate', self.edit_image)
        self.widgets.get_object('context-menu-save').connect('activate', self.save_image)
        self.widgets.get_object('context-menu-back').connect('activate', self.go_back)
        self.widgets.get_object('context-menu-forward').connect('activate', self.go_forward)
        self.widgets.get_object('context-menu-quit').connect('activate', self.quit)
        self.widgets.get_object('context-menu-preferences').connect('activate', self.edit_preferences)
        
        # Entry events:
        self.widgets.get_object('entry').connect('insert-text', self.entry_contents_changed)
        self.widgets.get_object('entry').connect('activate', self.entry_activated)
        
        # Setup the accelerators:
        accel_group = gtk.AccelGroup()
        self.add_accel_group(accel_group)
        
        # Key values = o, w, q:
        self.widgets.get_object('context-menu-open').add_accelerator('activate', accel_group, 111, gtk.gdk.CONTROL_MASK, (gtk.ACCEL_LOCKED))
        self.widgets.get_object('context-menu-close').add_accelerator('activate', accel_group, 119, gtk.gdk.CONTROL_MASK, (gtk.ACCEL_LOCKED))
        self.widgets.get_object('context-menu-quit').add_accelerator('activate', accel_group, 113, gtk.gdk.CONTROL_MASK, (gtk.ACCEL_LOCKED))
        
        # Key values = backspace, page up, back arrow:
        self.widgets.get_object('context-menu-back').add_accelerator('activate', accel_group, 65288, 0, (gtk.ACCEL_LOCKED))
        self.widgets.get_object('context-menu-back').add_accelerator('activate', accel_group, 65365, 0, (gtk.ACCEL_LOCKED))
        self.widgets.get_object('context-menu-back').add_accelerator('activate', accel_group, 65361, 0, (gtk.ACCEL_LOCKED))
        
        # Key values = spacebar, page down, forward arrow:
        self.widgets.get_object('context-menu-forward').add_accelerator('activate', accel_group, 32, 0, (gtk.ACCEL_LOCKED))
        self.widgets.get_object('context-menu-forward').add_accelerator('activate', accel_group, 65366, 0, (gtk.ACCEL_LOCKED))
        self.widgets.get_object('context-menu-forward').add_accelerator('activate', accel_group, 65363, 0, (gtk.ACCEL_LOCKED))
        
        # See the key_pressed method for more 'pseudo accelerators'
        
        # Resize window according to preferences:
        self.resize(self.preferences.getint('Window', 'width'),
                    self.preferences.getint('Window', 'height'))
        
        if self.preferences.getboolean('Window', 'maximized'):
            self.maximize()
        
        if self.preferences.getboolean('Window', 'fullscreen'):
            self.widgets.get_object('fullscreen_button').set_active(True)
        
        if not self.preferences.getboolean('Window', 'show_toolbar'):
            self.widgets.get_object('toolbar').hide()
        
        self.scale = self.preferences.getint('Image', 'scale')
        
        self.widgets.get_object('context-menu').attach_to_widget(self.widgets.get_object('viewport'), lambda *args:None)
        
        # Work around a bug in glade-3:
        self.widgets.get_object('image').clear()
        
        # Display the widgets:
        self.set_icon_name('image')
        self.set_title('Color Walk')
        self.add(self.widgets.get_object('vbox'))
        self.set_widget_sensitivity(False)
        self.show()
        
        # This allows us to reset the background to the original GTK style 
        # without destroying the widget:
        self.default_background = self.widgets.get_object('viewport').style.bg[gtk.STATE_NORMAL].to_string()
        self.set_background_color()
        
        # Open a file passed on the command line:
        if file:
            self.open(self.widgets.get_object('open_button'), file=file)
    
    def about(self, button):
        '''A callback connected to the about button's clicked signal. Shows the
        about dialog.'''
        
        dialog = ColorWalk.AboutDialog()
        if dialog.run():
            dialog.destroy()
    
    def close(self, button):
        '''A callback connected to the close button's clicked signal. Closes the
        file and resets the title, image, and all the toolbar widgets.'''
        
        if self.open_file:
            self.close_file()
            self.set_title('Color Walk')
            self.widgets.get_object('entry').set_text('')
            self.widgets.get_object('label').set_text('')
            self.set_widget_sensitivity(False)
            self.widgets.get_object('image').clear()
    
    def close_file(self):
        '''Reset all relevant variables and delete the temporary directory.'''
        
        self.current_pixbuf = None
        self.next_pixbuf = None
        self.prev_pixbuf = None
        
        self.index = 0
        self.images = []
        self.open_file = None
        
        if self.temp_dir:
            shutil.rmtree(self.temp_dir)
            self.temp_dir = None
    
    def edit_image(self, widget):
        '''A callback connected to the edit context menu item's activate signal.
        It launches a helper application (like the gimp) to edit the image.'''
        
        self.show_status_message('Running <i>%s %s</i> ...' % (self.preferences.get('Preferences', 'editor'), os.path.join(self.temp_dir, self.images[self.index])))
        
        subprocess.Popen([self.preferences.get('Preferences', 'editor'), os.path.join(self.temp_dir, self.images[self.index])])
    
    def edit_preferences(self, widget):
        '''A callback connected to the preferences button's clicked signal.
        Displays a dialog containing the application's options.'''
        
        dialog = ColorWalk.PreferencesDialog(self)
        
        if dialog.run():
            dialog.save()
            dialog.destroy()
            self.reload_preferences()
    
    def entry_activated(self, entry):
        '''A callback connected to the entry's activate signal. First the text
        is verified and then, if it's numerical, the correct page is opened.'''
        
        def fail():
            '''This is run when what's entered is invalid. It resets the entry
            widget and removes the focus from the entry.'''
            
            entry.set_text(str(self.index + 1))
            self.unfocus()
        
        try:
            index = int(entry.get_text()) - 1
            
            if index >= 0 and index < len(self.images):
                self.index = index
                
                self.reset_scrollbars()
                self.set_widget_state()
                
                reload_all(self)
                
            else:
                # The number falls outside the actual number of images.
                fail()
        except ValueError:
            # Non-numerical value.
            fail()
    
    def entry_contents_changed(self, entry, text, text_length, pointer):
        '''A callback connected to the entry's contents-changed signal. Prevents
        any non numerical characters from being entered into the entry.'''
        
        try:
            int(text)
        except ValueError:
            entry.stop_emission('insert-text')
    
    def get_available_space(self):
        '''Returns the amount of space that the image can occupy in pixels.'''
        
        # TODO: Find a way to get the scrollbar's actual width.
        scrollbar = 20
        
        # TODO: If scrollbars aren't actually going to be displayed, account for
        # that.
        
        height = self.height - self.widgets.get_object('toolbar').size_request()[0]
        width = self.width - scrollbar
        
        return (width, height)
    
    def go_back(self, button):
        '''A callback connected to the back button's clicked signal. Displays
        the previous page.'''
        
        if self.index >= 0:
            if self.prev_pixbuf:
                self.index -= 1
                
                self.next_pixbuf = self.current_pixbuf
                self.current_pixbuf = self.prev_pixbuf
                self.prev_pixbuf = None
                
                self.reset_scrollbars()
                self.set_widget_state()
                
                self.widgets.get_object('image').set_from_pixbuf(self.current_pixbuf)
                
                preload_images(self, next=False, prev=True)
    
    def go_forward(self, button):
        '''A callback connected to the forward button's clicked signal. Displays
        the next page.'''
        
        if self.index < len(self.images):
            if self.next_pixbuf:
                self.index += 1
                
                self.prev_pixbuf = self.current_pixbuf
                self.current_pixbuf = self.next_pixbuf
                self.next_pixbuf = None
                
                self.reset_scrollbars()
                self.set_widget_state()
                
                self.widgets.get_object('image').set_from_pixbuf(self.current_pixbuf)
                
                preload_images(self, next=True, prev=False)
    
    def go_to_index(self, index):
        '''Displays the page refered to by the value of index. This is only used
        internally with safe values for index, so we don't need to check the
        value of index here.'''
        
        self.index = index
        
        self.reset_scrollbars()
        self.set_widget_state()
        
        reload_all(self)
    
    def help(self, widget):
        '''A callback connected to the help button's clicked signal. Displays a
        dialog listing all the keyboard shortcuts.'''
        
        dialog = ColorWalk.HelpDialog(self)
        
        if dialog.run():
            dialog.destroy()
    
    def image_clicked(self, viewport, event):
        '''A callback connected to the viewport's button-pressed-event. Displays
        a menu whent he right mouse button is pressed.'''
        
        if event.button == 3:
            if not self.preferences.get('Preferences', 'editor'):
                self.widgets.get_object('context-menu-edit').set_sensitive(False)
            else:
                if self.open_file:
                    self.widgets.get_object('context-menu-edit').set_sensitive(True)
            
            self.widgets.get_object('context-menu').popup(None, None, None, event.button, event.time, None)
    
    def key_pressed(self, widget, event):
        '''A callback connected to the window's key-pressed-event. Does 
        something depending on the key.'''
        
        if event.keyval == 65480: # F11
            self.widgets.get_object('fullscreen_button').set_active(not self.widgets.get_object('fullscreen_button').get_active())
        
        if event.keyval == 65470: # F1
            self.help(widget)
        
        if self.open_file:
            if event.keyval == 65360: # Home
                self.go_to_index(0)
            
            elif event.keyval == 65367: # End
                self.go_to_index(len(self.images) - 1)
    
    def open(self, button, file=None):
        '''A callback connected to the open button's clicked signal. Can also be
        called with a file as an argument to open files passed as command line
        arguments. If the file is valid the archive is opened. Otherwise, the 
        fail method is called and an error message is displayed.'''
        
        button.set_sensitive(False)
        
        if file:
            file = os.path.abspath(file)
            self.browse_dir = os.path.split(file)[0]
            
            if not os.path.exists(file):
                file = None
        
        else:
            file = choose_file(self.browse_dir)
        
            try:
                self.browse_dir = os.path.split(file)[0]
                
                if self.open_file:
                    self.close_file()
            
            except AttributeError:
                pass
        
        if file:
            ext = os.path.splitext(file)[1]
            
            if ext == '.zip' or ext == '.cbz':
                self.temp_dir = tempfile.mkdtemp(prefix='colorwalk-%s-' % os.environ['USER'])
                command = 'unzip -j \"%s\" -d \"%s\"' % (file, self.temp_dir)
                
            elif ext == '.rar' or ext == '.cbr':
                self.temp_dir = tempfile.mkdtemp(prefix='colorwalk-%s-' % os.environ['USER'])
                command = 'unrar e \"%s\" \"%s\"' % (file, self.temp_dir)
                
            else:
                command = None
        
        else:
            command = None
        
        if command:
            # It's less confusing if we get rid of any old image first:
            self.widgets.get_object('image').clear()
            
            def worker():
                '''Runs in the background to avoid blocking the UI. Opens the
                required images.'''
                
                self.lock.acquire()
                
                self.widgets.get_object('status_label').set_markup('Opening <i>%s</i> ...' % os.path.split(file)[1])
                self.widgets.get_object('status_box').show()
                
                p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                
                while p.poll() == None:
                    # Wait until the archive is done extracting before we do
                    # anything else.
                    self.widgets.get_object('progressbar').pulse()
                    time.sleep(0.1)
                
                for f in os.listdir(self.temp_dir):
                    # Only add files with a valid extension to the list of
                    # images.
                    if os.path.splitext(f)[1].lower() in IMAGE_EXTENSIONS:
                        self.images.append(f)
                
                if not len(self.images):
                    button.set_sensitive(True)
                    self.show_status_message('<i>%s</i> cannot be opened because it does not contain any images.' % os.path.split(file)[1])
                
                else:
                    self.images.sort(key=str.lower)
                    self.open_file = file
                    
                    self.reset_scrollbars()
                    
                    self.current_pixbuf = new_pixbuf(os.path.join(self.temp_dir, self.images[0]), self.scale, *self.get_available_space())
                    self.widgets.get_object('image').set_from_pixbuf(self.current_pixbuf)
                    
                    button.set_sensitive(True)
                    self.set_widget_state()
                    self.set_widget_sensitivity(True)
                    self.widgets.get_object('status_box').hide()
                    
                    self.next_pixbuf = new_pixbuf(os.path.join(self.temp_dir, self.images[1]), self.scale, *self.get_available_space())
                
                self.lock.release()
            
            self.worker = threading.Thread(target=worker)
            
            self.worker.start()
        
        elif file and not command:
            button.set_sensitive(True)
            self.show_status_message('<i>%s</i> cannot be opened because it is not a valid archive file.' % os.path.split(file)[1])
        
        else:
            button.set_sensitive(True)
    
    def quit(self, window, event=None):
        '''A callback connected to the window's delete-event signal. It deletes
        the temporary directory, if it exists, saves the preferences, and
        destroys the window.'''
        
        self.close_file()
        
        if self.width_old and self.height_old:
            self.preferences.set('Window', 'width', str(self.width_old))
            self.preferences.set('Window', 'height', str(self.height_old))
        else:
            self.preferences.set('Window', 'width', str(self.width))
            self.preferences.set('Window', 'height', str(self.height))
        
        self.preferences.set('Window', 'maximized', str(self.maximized))
        self.preferences.set('Image', 'scale', str(self.scale))
        self.preferences.save()
        
        gtk.main_quit()
        sys.exit(0)
    
    def reload_preferences(self):
        '''Applies the preference values to their related widgets. This is run 
        after the preferences dialog is closed.'''
        
        if self.preferences.getboolean('Window', 'show_toolbar'):
            self.widgets.get_object('toolbar').show()
        else:
            self.widgets.get_object('toolbar').hide()
        
        self.set_background_color()
    
    def reset_scrollbars(self):
        '''This method moves the scrollbars back to their default positions.'''
        
        # TODO: Add support for RTL
        
        viewport = self.widgets.get_object('scrolledwindow')
        hadj = viewport.get_hadjustment()
        vadj = viewport.get_vadjustment()
        vadj.set_value(vadj.lower)
        hadj.set_value(hadj.lower)
        viewport.set_hadjustment(hadj)
        viewport.set_vadjustment(vadj)
    
    def save_image(self, widget):
        '''A callback connected to the save context menu item's activate signal.
        This allows the user to save the currently displayed image somewhere.'''
        
        dialog = gtk.FileChooserDialog(title='Save File', action=gtk.FILE_CHOOSER_ACTION_SAVE, buttons=(gtk.STOCK_CANCEL, gtk.RESPONSE_REJECT, gtk.STOCK_SAVE, gtk.RESPONSE_ACCEPT))
        dialog.set_current_folder(self.browse_dir)
        dialog.set_current_name(self.images[self.index])
        dialog.set_do_overwrite_confirmation(True)
        
        if dialog.run() == gtk.RESPONSE_ACCEPT:
            file = dialog.get_filename()
            
            shutil.copyfile(os.path.join(self.temp_dir, self.images[self.index]), file)
        
        dialog.destroy()
    
    def set_background_color(self):
        '''Sets the background color of the image viewing area from the 
        preference value.'''
        
        pref = self.preferences.get('Preferences', 'background')
        
        if pref == 'match':
            if numpy:
                if self.open_file:
                    self.widgets.get_object('viewport').modify_bg(gtk.STATE_NORMAL, gtk.gdk.color_parse(find_average_border_color(self.current_pixbuf.get_pixels_array(), self.current_pixbuf.get_width(), self.current_pixbuf.get_height())))
            
            # Bit of a hack. Avoid a segfault if numpy isn't installed but the
            # preference is set ot 'match'.
            else:
                pref = 'theme'
        
        elif pref == 'theme':
            self.widgets.get_object('viewport').modify_bg(gtk.STATE_NORMAL, gtk.gdk.color_parse(self.default_background))
        
        else:
            self.widgets.get_object('viewport').modify_bg(gtk.STATE_NORMAL, gtk.gdk.color_parse(pref))
    
    def set_widget_sensitivity(self, bool):
        '''Calls the toolbar buttons and menu items set_sensitive methods with
        the value of bool.'''
        
        self.widgets.get_object('close_button').set_sensitive(bool)
        self.widgets.get_object('back_button').set_sensitive(bool)
        self.widgets.get_object('forward_button').set_sensitive(bool)
        self.widgets.get_object('normal_button').set_sensitive(bool)
        self.widgets.get_object('fit_button').set_sensitive(bool)
        self.widgets.get_object('entry').set_sensitive(bool)
        self.widgets.get_object('label').set_sensitive(bool)
        
        # Context menu widgets:
        self.widgets.get_object('context-menu-close').set_sensitive(bool)
        self.widgets.get_object('context-menu-back').set_sensitive(bool)
        self.widgets.get_object('context-menu-forward').set_sensitive(bool)
        self.widgets.get_object('context-menu-edit').set_sensitive(bool)
        self.widgets.get_object('context-menu-save').set_sensitive(bool)
    
    def set_widget_state(self):
        '''Updates properites of any widget that may change depending on whether
        an image is being displayed.'''
        
        self.set_title('%s - %s' % (os.path.split(self.open_file)[1], self.images[self.index]))
        self.widgets.get_object('entry').set_text(str(self.index + 1))
        self.widgets.get_object('label').set_text('of %d' % len(self.images))
        
        self.set_background_color()
        
        self.unfocus()
        
        if self.index == 0:
            self.widgets.get_object('back_button').set_sensitive(False)
        else:
            self.widgets.get_object('back_button').set_sensitive(True)
        
        if self.index == len(self.images) - 1:
            self.widgets.get_object('forward_button').set_sensitive(False)
        else:
            self.widgets.get_object('forward_button').set_sensitive(True)
    
    def show_status_message(self, message, timeout=10):
        '''If a file cannot be opened this method is run to display an error
        message to the user.'''
        
        self.widgets.get_object('progressbar').hide()
        self.widgets.get_object('status_label').set_markup(message)
        self.widgets.get_object('status_box').show()
        
        def statusbar_hide():
            '''Hides the statusbar and then returns False to remove the glib
            timeout.'''
            
            self.widgets.get_object('status_box').hide()
            return False
        
        glib.timeout_add_seconds(timeout, statusbar_hide)
    
    def state_changed(self, widget, event):
        '''A callback connected to the window's window-state-event signal. This
        is used to keep track of whether the window is maximized or not.'''
        
        if event.new_window_state == gtk.gdk.WINDOW_STATE_MAXIMIZED:
            self.maximized = True
        else:
            self.maximized = False
    
    def toggle_fullscreen(self, button):
        '''A callback connected to the fullscreen button's clicked signal.
        Changes the fullscreen property of the window depending on thes state of
        the button.'''
        
        if button.get_active():
            self.width_old = self.width
            self.height_old = self.height
            
            self.fullscreen()
        else:
            self.width_old = None
            self.height_old = None
            
            self.unfullscreen()
    
    def toggle_scale(self, button):
        '''A callback connected to the two scale button's clicked signals. It
        sets the window's scale property depending on which button is active.
        The scale property affects the way that images are loaded.'''
        
        old_scale = self.scale
        
        if button.get_active():
            if button is self.widgets.get_object('normal_button'):
                self.scale = DEFAULT_SIZE
            else:
                self.scale = FIT_BY_WIDTH
            
            if self.scale != old_scale:
                reload_all(self)
    
    def unfocus(self):
        '''Focus the forward button so that spacebar presses don't activate any
        other widget.'''
        
        self.widgets.get_object('forward_button').grab_focus()
    
    def window_resized(self, window, allocation):
        '''A callback connected to the window's frame-event signal. It detects
        whether the window has been resized and if it has, resizes the image
        displayed to still properly fit the window.'''
        
        if (self.width != allocation.width or self.height != allocation.height):
            self.width = allocation.width
            self.height = allocation.height
            
            if self.open_file:
                reload_all(self)
    

if __name__ == '__main__':
    
    parser = optparse.OptionParser(usage='Usage: %prog [options] FILE')
    parser.add_option('--generate-thumbnail', action='store_true', dest='thumbnail', help='create a thumbnail file for a comic book')
    options, args = parser.parse_args()
    
    if options.thumbnail:
        if not args:
            print 'Usage: colorwalk --generate-thumbnail FILE\n\nYou must specify a file'
        else:
            print 'Do something here'
        
        sys.exit(0)
    
    gtk.gdk.threads_init()
    
    ui = find_ui_definition()
    
    if not ui:
        sys.exit('A required file, colorwalk.ui, is missing. Unable to continue.')
    
    if args:
        Window(ui, file=args[0])
        gtk.main()
    
    else:
        Window(ui)
        gtk.main()
