#!/usr/bin/env python

import sys, os, subprocess, optparse

VERSION = '0.1.0'
PREFIX = '/usr'

parser = optparse.OptionParser()
parser.add_option('--prefix', dest='prefix', help='define an alternate location to install to')
(options, args) = parser.parse_args()

if options.prefix:
    PREFIX = options.prefix

print 'Installing Color Walk %s :\n' % VERSION

subprocess.call(['mkdir', '-p', os.path.join(PREFIX, 'share/colorwalk')])

print 'Copying colorwalk.ui to %s/share/colorwalk ...' % PREFIX ,
retval = subprocess.call(['install', 'colorwalk.ui', os.path.join(PREFIX, 'share/colorwalk/colorwalk.ui')])
if retval:
    print 'Failed'
    print '\nColor Walk failed to install.'
    sys.exit(1)
else:
    print 'Done'

print 'Copying colorwalk.desktop to %s/share/applications ...' % PREFIX ,
retval = subprocess.call(['install', 'colorwalk.desktop', os.path.join(PREFIX, 'share/applications/colorwalk.desktop')])
if retval:
    print 'Failed'
    print '\nColor Walk failed to install.'
    sys.exit(1)
else:
    print 'Done'

print 'Copying colorwalk to %s/bin ...' % PREFIX ,
retval = subprocess.call(['install', 'colorwalk', os.path.join(PREFIX, 'bin/colorwalk')])
if retval:
    print 'Failed'
    print '\nColor Walk failed to install.'
    sys.exit(1)
else:
    print 'Done'

print '\nColor Walk %s is now installed.' % VERSION
